spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:}
      password: ${MONGODB_PASSWORD:}
      database: ${MONGODB_DATABASE:csv-rest-api}

tenancy:
  admin-username: ${TENANT_ADMIN_USERNAME:}
  admin-password: ${TENANT_ADMIN_PASSWORD:}

springdoc:
  packages-to-scan: st.emberdex.csvapi

logging:
  level:
    st:
      emberdex:
        csvapi: ${LOGGING_LEVEL:INFO}
